version: '3.8'

services:
  octoprint:
    image: octoprint/octoprint
    restart: unless-stopped
    ports:
      - 7180:80
    volumes:
      - ./docker-data/octoprint:/octoprint/octoprint
      - ./octoprint_Spoolman:/octoprint/octoprint/plugins/Spoolman
  spoolman:
    image: ghcr.io/donkie/spoolman:latest
    restart: unless-stopped
    volumes:
      - ./docker-data/spoolman:/home/app/.local/share/spoolman
    ports:
      - 7181:8000
    environment:
      TZ: Europe/Warsaw
      SPOOLMAN_DB_TYPE: postgres
      SPOOLMAN_DB_HOST: spoolman_database
      SPOOLMAN_DB_PORT: 5432
      SPOOLMAN_DB_NAME: spoolman
      SPOOLMAN_DB_USERNAME: spoolman_user
      SPOOLMAN_DB_PASSWORD: spoolman_dev_password
    depends_on:
      - spoolman_database
  spoolman_database:
    image: postgres:16.1-bullseye
    restart: unless-stopped
    environment:
      POSTGRES_USER: spoolman_user
      # Development container password, DO NOT REUSE ELSEWHERE
      POSTGRES_PASSWORD: spoolman_dev_password
      POSTGRES_DB: spoolman
    volumes:
      - ./docker-data/spoolman_db:/var/lib/postgresql/data/
